-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public."Device_style_value"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FK_Device_property_value" integer NOT NULL,
    "FK_Style_property" integer NOT NULL,
    "Value" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Device_style_value_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE IF NOT EXISTS public."Style_property"
(
    "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Style_property_pkey" PRIMARY KEY ("ID")
);


ALTER TABLE IF EXISTS public."Device_style_value"
    ADD CONSTRAINT "FK_Device_property_value" FOREIGN KEY ("FK_Device_property_value")
    REFERENCES public."Device_property_value" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Device_style_value"
    ADD CONSTRAINT "FK_Style_property" FOREIGN KEY ("FK_Style_property")
    REFERENCES public."Style_property" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;